### ISSUE TITLE
Installing the twitter toolkit

### ISSUE THREAD

**Issue by Camaraarthur** [BHoM/Twitter_Toolkit#10]
How do i install this toolkit into bhom?

**Comment by FraserGreenroyd** [comment]
Hi @Camaraarthur sorry for the late response, I've only just seen this issue during our issue closure sprint!

To install this toolkit into the BHoM it would be best to do the following:

 - Take the latest BHoM beta from [the website](http://bhom.xyz) (scroll to the bottom and you should find a link)
 - Compile this toolkit

If this toolkit compiles, the DLLs should be copied to the `C:/ProgramData/BHoM/Assemblies` folder, and the beta will give you everything else you'd need (for UI management, etc.).

If the toolkit does not compile, then it would need some code changes to fix - the odds are high that this may be the case as this toolkit has not been touched in a long time by our team, so it may be out of sync to the BHoM/BHoM_Engine framework.

Feel free to reach out directly (tag me or email) if you need any other support or if the toolkit doesn't compile and you need some support to get it back to a compiling state, happy to help if I can 😄
